### ISSUE TITLE
add any information in logs (TechnicalException) if technical problem.

### ISSUE THREAD

**Issue by sgrillon14** [NoraUi/NoraUi#104]
## Summary

add any information in logs if technical problem.

## Expected Behavior

noraui custom message in a TechnicalException

## Current Behavior

java.lang.ArrayIndexOutOfBoundsException: 1
	at com.github.noraui.application.steps.CommonSteps.clickOn(CommonSteps.java:387)
	at ✽.Je clique sur 'demo.DemoPage-'(file:src/test/resources/steps/bonjour.feature:81)

java.lang.ArrayIndexOutOfBoundsException: 1
	at com.github.noraui.application.steps.CommonSteps.clickOn(CommonSteps.java:387)
	at ✽.I click on 'demo.DemoPage-'(file:src/test/resources/steps/hello.feature:80)

## Possible Solution

add check on `pageElement`: 

```
public void clickOn(String pageElement, List<GherkinStepCondition> conditions) throws TechnicalException, FailureException {
        String page = pageElement.split("-")[0];
        String elementName = pageElement.split("-")[1];
        ...
```

## Steps to Reproduce (for bugs)

use a `@When("I click on {string}(\\?)")` without second element: 

`I click on 'demo.DemoPage-'`

## Context & Motivation

V4.0.0 more strong in case of bug

## Your Environment

* Robot generated by NoraUi Version: V4.0.0-SNAPSHOT
* NoraUi Version used: V4.0.0-SNAPSHOT
* Operating System and version: Unix and Windows
* Data input provider: N/A
* Data output provider: N/A
* Browser and version: Chrome 75
* Link to your project: http://noraui.github.io

**Comment by sgrillon14** [comment]
fix this with PageElement past from gherkin to Cucumber steps

**Comment by sgrillon14** [comment]
fix with https://github.com/NoraUi/NoraUi/blob/master/src/main/java/com/github/noraui/cucumber/config/CucumberTypeRegistryConfigurer.java
