### ISSUE TITLE
AuthUT KO after update chromedriver to 77

### ISSUE THREAD

**Issue by sgrillon14** [NoraUi/NoraUi#115]
## Describe the bug

```
Starting ChromeDriver 77.0.3865.40 (f484704e052e0b556f8030b65b953dce96503217-refs/branch-heads/3865@{#442}) on port 11429
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1568318970.020][SEVERE]: bind() failed: Cannot assign requested address (99)
Sep 12, 2019 8:09:30 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
[ERROR] Tests run: 4, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 6.182 s <<< FAILURE! - in com.github.noraui.browser.AuthUT
[ERROR] testPageBehindCookieAuthentication(com.github.noraui.browser.AuthUT)  Time elapsed: 1.054 s  <<< FAILURE!
java.lang.AssertionError: 
Exception thrown: unable to set cookie
  (Session info: chrome=77.0.3865.75)
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'localhost', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-101-generic', java.version: '1.8.0_151'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 77.0.3865.75, chrome: {chromedriverVersion: 77.0.3865.40 (f484704e052e0..., userDataDir: /tmp/.com.google.Chrome.t0Q5tx}, goog:chromeOptions: {debuggerAddress: localhost:39433}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: accept}
Session ID: 2d6f7fb2af9dd2fb8fe2f690c33f0efb
	at com.github.noraui.browser.AuthUT.testPageBehindCookieAuthentication(AuthUT.java:119)
[ERROR] testPageBehindAuthenticationWithWrongCredentials(com.github.noraui.browser.AuthUT)  Time elapsed: 0.996 s  <<< FAILURE!
java.lang.AssertionError: The requested page content must not respond 'OK'.
	at com.github.noraui.browser.AuthUT.testPageBehindAuthenticationWithWrongCredentials(AuthUT.java:84)
```
## Steps to Reproduce (for bugs)

1. run AuthUT
2.
3.
4.

## Context & Motivation

build master of NoraUi

## Your Environment

* Robot generated by NoraUi Version: V4.0.0-SNAPSHOT
* NoraUi Version used: V4.0.0-SNAPSHOT
* Operating System and version: Unix and Windows
* Browser and version: Chrome 77

**Comment by sgrillon14** [comment]
I fix 1st ko with https://github.com/NoraUi/NoraUi/commit/ce7483715d13427fe87f041ae80029cf97aa9767

**Comment by sgrillon14** [comment]
https://stackoverflow.com/questions/57959998/chromewebdriver-unable-to-set-cookie-when-i-update-chrome-to-77
