### ISSUE TITLE
The last column of the data file must belong to '[RÚsultat, Result]'

### ISSUE THREAD

**Issue by JarekLipsko** [NoraUi/NoraUi#14]
I use  Intellij IDE + Windows 7 with NoraUi 2.6.3

I run this Maven command:
`mvn clean install -PpreIC,scenarioInitiator,unit-tests -Dcucumber.options="--tags '@bonjour'" -Dmaven.test.failure.ignore=true`

I have this logs on my console:
```
[2017-10-04 20:10:02]: Data provider used is CSV.
[2017-10-04 20:10:03]: /!\ Wrong data file (IOException, EmptyDataFileContentException or WrongDataFileFormatException). /!\
noraui.exception.data.WrongDataFileFormatException: /!\ The last column of the data file must belong to '[RÚsultat, Result]'. /!\
        at noraui.data.csv.CsvDataProvider.initColumns(CsvDataProvider.java:155)
        at noraui.data.csv.CsvDataProvider.prepare(CsvDataProvider.java:41)
        at noraui.indus.MavenRunCounter.countNbCasFailuresAndSkipped(MavenRunCounter.java:203)
        at noraui.indus.MavenRunCounter.countNbCasFailuresAndSkipped(MavenRunCounter.java:84)
        at noraui.indus.MavenRunCounter.count(MavenRunCounter.java:59)
        at noraui.indus.Counter.main(Counter.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
        at java.lang.Thread.run(Thread.java:748)[2017-10-04 20:10:02]: Data provider used is CSV.
[2017-10-04 20:10:03]: /!\ Wrong data file (IOException, EmptyDataFileContentException or WrongDataFileFormatException). /!\
noraui.exception.data.WrongDataFileFormatException: /!\ The last column of the data file must belong to '[RÚsultat, Result]'. /!\
        at noraui.data.csv.CsvDataProvider.initColumns(CsvDataProvider.java:155)
        at noraui.data.csv.CsvDataProvider.prepare(CsvDataProvider.java:41)
        at noraui.indus.MavenRunCounter.countNbCasFailuresAndSkipped(MavenRunCounter.java:203)
        at noraui.indus.MavenRunCounter.countNbCasFailuresAndSkipped(MavenRunCounter.java:84)
        at noraui.indus.MavenRunCounter.count(MavenRunCounter.java:59)
        at noraui.indus.Counter.main(Counter.java:38)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by sgrillon14** [comment]
I need create a FileInputStream wrapped in an InputStreamReader instead of just a FileReader. (FileReader always uses the default encoding for the system.) Specify the encoding to use when you create the InputStreamReader, and if you've picked the right one, everything should start working.

**Comment by sgrillon14** [comment]
all files use by NoraUi are encoded in UTF-8

**Comment by sgrillon14** [comment]
Fixed in V3.x.x
