### ISSUE TITLE
TechnicalException error: "Scenario Outline:" controler fail

### ISSUE THREAD

**Issue by sgrillon14** [NoraUi/NoraUi#140]
## Describe the bug

[2020-04-17 18:46:35]: TechnicalException error:
com.github.noraui.exception.TechnicalException: [ERROR] The feature « jouerAuJeuDesLogos » must contain at least 1 instruction "Scenario Outline:" ("Plan du Scénario:" in french).
        at com.github.noraui.indus.MavenRunCounter.count(MavenRunCounter.java:107)
        at com.your.company.indus.Counter.main(Counter.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:748)
[INFO]

## Steps to Reproduce (for bugs)

1. mvn archetype:generate -B -DarchetypeGroupId=com.github.noraui -DarchetypeArtifactId=noraui-archetype -DarchetypeVersion=4.2.3.0-SNAPSHOT -DgroupId=com.your.company -DartifactId=robot -Dversion=0.0.1-SNAPSHOT -DinteractiveMode=false 
2. cd robot
3. mvn clean test javadoc:javadoc -B -U -Dcucumber.options="--tags '@loginLogout or @playToLogoGame or @jouerAuJeuDesLogos or @search'" -Pjavadoc,preIC,scenarioInitiator,ci,unit-tests,postIC -Dmaven.test.failure.ignore=true -Dcrypto.key=secret
4.

## Your Environment

* Robot generated by NoraUi Version: V4.2.3.0-SNAPSHOT
* NoraUi Version used: V4.2.3-SNAPSHOT
* Operating System and version: Unix and Windows
* Data input provider: Excel
* Data output provider: Excel
* Browser and version: Chrome 80
* WebDriver and version: ChromeDriver 80

**Comment by sgrillon14** [comment]
this bug com from noraui-archetype, please change your .feature file encoding
