### ISSUE TITLE
CLI remove model error

### ISSUE THREAD

**Issue by sgrillon14** [NoraUi/NoraUi#154]
use CLI:

What do you want ?
    0 => exit NoraUi CLI
    1 => add new application
    2 => add new scenario
    3 => add new model
    4 => remove application
    5 => remove scenario
    6 => remove model
    7 => encrypt data
    8 => decrypt data
    9 => status
6
Enter index application number:
    1) logogame
1
Enter index model number:
    1) logo
1
Remove model named [logo] in application named [logogame]
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at com.github.noraui.cli.model.NoraUiCliFile.removeModel(NoraUiCliFile.java:121)
	at com.github.noraui.cli.NoraUiCommandLineInterface.removeModelInCliFileFeature(NoraUiCommandLineInterface.java:993)
	at com.github.noraui.cli.NoraUiCommandLineInterface.removeModel(NoraUiCommandLineInterface.java:980)
	at com.github.noraui.cli.NoraUiCommandLineInterface.runFeature(NoraUiCommandLineInterface.java:558)
	at com.github.noraui.cli.NoraUiCommandLineInterface.runCli(NoraUiCommandLineInterface.java:172)
	at com.xxx.cli.NoraUiCLI.main(NoraUiCLI.java:33)

**Comment by sgrillon14** [comment]
resolved in 4.5.0+

**Comment by sgrillon14** [comment]
fix by [704d23f](https://github.com/NoraUi/NoraUi/commit/704d23fd9c2c319dbd98f5e894cf47c3ce54ea06)
