### ISSUE TITLE
Unit test KO on RestJson (initColumns)

### ISSUE THREAD

**Issue by sgrillon14** [NoraUi/NoraUi#68]
2018-04-30 21:25:52]: Context > initializeEnv()
[2018-04-30 21:25:52]: Reading properties file (demoRestJson.properties).
[2018-04-30 21:25:52]: Loaded properties from demoRestJson.properties = {model.packages=com.github.noraui.application.model, countries=http://localhost:4200/#/login, dataProvider.out.type=REST, dataProvider.rest.type=JSON, selectors.version=V1, logogame=https://noraui.github.io/demo/logogame/v1, dataProvider.rest.hostname=http://localhost, dataProvider.in.type=REST, timeout=3, authentication=, dataProvider.rest.port=8084, demo=https://noraui.github.io/demo/hello, display.stacktrace=true, https_proxy=, no_proxy=, locale=en, http_proxy=, browser=chrome}.
[2018-04-30 21:25:52]: Current locale used: en.
[2018-04-30 21:25:52]: Reading properties file (scenarios.properties).
[2018-04-30 21:25:52]: Loaded properties from scenarios.properties = {jouerAuJeuDesLogos=/steps/, hello=/steps/, LoginLogout=/steps/, playToLogoGame=/steps/, blog=/steps/, bonjour=/steps/}.
[2018-04-30 21:25:52]: Data provider used is REST.
[2018-04-30 21:25:52]: error MavenRunCounter.countNbCasFailuresAndSkipped()
java.lang.NullPointerException: null
	at com.github.noraui.data.rest.RestDataProvider.initColumns(RestDataProvider.java:168)
	at com.github.noraui.data.rest.RestDataProvider.prepare(RestDataProvider.java:75)
	at com.github.noraui.indus.MavenRunCounter.countNbCasFailuresAndSkipped(MavenRunCounter.java:252)
	at com.github.noraui.indus.MavenRunCounter.countNbCasFailuresAndSkipped(MavenRunCounter.java:94)
	at com.github.noraui.indus.MavenRunCounter.count(MavenRunCounter.java:69)
	at com.github.noraui.indus.Counter.main(Counter.java:51)
	at com.github.noraui.indus.CounterUT.testRestJsonCounter(CounterUT.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
[2018-04-30 21:25:52]: Scenario: hello => step: 87 and cases: 0 -->  runs: 0, failures: 0, errors: 0 and skips: 0
[2018-04-30 21:25:52]: [RestJson] > <EXPECTED_RESULTS_1>0 Scenarios)</EXPECTED_RESULTS_1>
[2018-04-30 21:25:52]: [RestJson] > <EXPECTED_RESULTS_2>0 Steps )</EXPECTED_RESULTS_2>

**Comment by sgrillon14** [comment]
Solve by commit [610138a](https://github.com/NoraUi/NoraUi/commit/610138ab538063b69b0d567aa92d0670a7fd9d7c)

**console:**
```
[2018-05-01 21:26:22]: Reading properties file (scenarios.properties).
[2018-05-01 21:26:22]: Loaded properties from scenarios.properties = {jouerAuJeuDesLogos=/steps/, hello=/steps/, LoginLogout=/steps/, playToLogoGame=/steps/, blog=/steps/, bonjour=/steps/}.
[2018-05-01 21:26:22]: Data provider used is REST.
[2018-05-01 21:26:22]: JSON response is: {"columns":["author","zip","city","element","element2","date","title"],"rows":null}
[2018-05-01 21:26:22]: Reflections took 11 ms to scan 2 urls, producing 8 keys and 16 values 
[2018-05-01 21:26:22]: JSON response is: 8
[2018-05-01 21:26:22]: JSON response is: 
[2018-05-01 21:26:22]: JSON response is: 8
[2018-05-01 21:26:22]: JSON response is: 24
[2018-05-01 21:26:22]: JSON response is: 8
[2018-05-01 21:26:22]: JSON response is: 18
[2018-05-01 21:26:22]: JSON response is: 8
[2018-05-01 21:26:22]: JSON response is: 
[2018-05-01 21:26:22]: JSON response is: 8
[2018-05-01 21:26:22]: JSON response is: 29
[2018-05-01 21:26:22]: JSON response is: 8
[2018-05-01 21:26:22]: JSON response is: 2
[2018-05-01 21:26:22]: JSON response is: 8
[2018-05-01 21:26:22]: JSON response is: 3
[2018-05-01 21:26:22]: JSON response is: 8
[2018-05-01 21:26:22]: JSON response is: 44
[2018-05-01 21:26:22]: JSON response is: 8
[2018-05-01 21:26:22]: Scenario: hello => step: 87 and cases: 8 -->  runs: 704, failures: 6, errors: 0 and skips: 402
[2018-05-01 21:26:22]: [RestJson] > <EXPECTED_RESULTS_1>8 Scenarios (6 failed, 2 passed)</EXPECTED_RESULTS_1>
[2018-05-01 21:26:22]: [RestJson] > <EXPECTED_RESULTS_2>696 Steps (6 failed, 402 skipped, 288 passed)</EXPECTED_RESULTS_2>
```
