### ISSUE TITLE
i18n fail on HTTP_SERVICE_ERROR_MESSAGE

### ISSUE THREAD

**Issue by Kaka69** [NoraUi/NoraUi#85]
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key HTTP_SERVICE_ERROR_MESSAGE
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at com.github.noraui.utils.Messages.getMessage(Messages.java:154)
	at com.github.noraui.utils.Messages.getMessage(Messages.java:132)
	at com.github.noraui.service.impl.HttpServiceImpl.get(HttpServiceImpl.java:52)
	at com.github.noraui.data.rest.RestDataProvider.initColumns(RestDataProvider.java:132)
	at com.github.noraui.data.rest.RestDataProvider.prepare(RestDataProvider.java:75)
	at com.github.noraui.indus.MavenRunCounter.countNbCasFailuresAndSkipped(MavenRunCounter.java:262)
	at com.github.noraui.indus.MavenRunCounter.countNbCasFailuresAndSkipped(MavenRunCounter.java:250)
	at com.github.noraui.indus.MavenRunCounter.count(MavenRunCounter.java:69)
	at com.github.noraui.indus.Counter.main(Counter.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)

**Comment by sgrillon14** [comment]
https://github.com/NoraUi/NoraUi/pull/86

**Comment by sgrillon14** [comment]
merged, you can find this in NoraUi V4.x.x
